# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAWRq_svjjXP7S-zLyuolytFEXjnH-_3
"""

import numpy as np

# Basic array
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(type(arr))
print(arr * 2)
print(arr + 5)

#basic infp
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr.size)
print(arr.shape)
print(arr.dtype)
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.std())

#2D Matrix
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix)
print(matrix.shape)
print(matrix[0][0])
print(matrix[1][2])
print(matrix[2][0])

#special arrays
import numpy as np

zeros = np.zeros((3, 3))
print(zeros)

ones = np.ones((2, 4))
print(ones)

arr = np.arange(0, 10, 2)
print(arr)

random = np.random.randint(1, 100, (3, 3))
print(random)

#Cell 5 — Indexing + Slicing
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[-1])
print(arr[2:4])
print(arr[::2])

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(matrix[0, :])
print(matrix[:, 1])
print(matrix[2, 1])

#Reshape + Flatten
import numpy as np

arr = np.arange(1, 10)
print(arr)

matrix = arr.reshape(3, 3)
print(matrix)

matrix2 = arr.reshape(1, 9)
print(matrix2)

matrix3 = arr.reshape(9, 1)
print(matrix3)

flat = matrix.flatten()
print(flat)

#array operation
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

print(a * 2)
print(b + 100)

print(a > 3)
print(b == 30)

#numpy and panda combo
import numpy as np
import pandas as pd

scores = np.random.randint(50, 100, 5)
names  = ["Devansh", "Rahul", "Priya",
          "John", "Sara"]

df = pd.DataFrame({
    "Name" : names,
    "Score": scores
})

print(df)
print(f"Average: {df['Score'].mean():.1f}")
print(f"Max    : {df['Score'].max()}")
print(f"Min    : {df['Score'].min()}")

#exercise for pratices
import numpy as np

# Exercise 1 — Salary array banao
salaries = np.array([40000, 60000, 55000,
                     42000, 80000])
print(f"Total  : {salaries.sum()}")
print(f"Average: {salaries.mean():.0f}")
print(f"Max    : {salaries.max()}")
print(f"Min    : {salaries.min()}")

# Exercise 2 — Filter
print(salaries[salaries > 50000])

# Exercise 3 — Reshape
matrix = salaries.reshape(1, 5)
print(matrix)

# Exercise 4 — Operations
hike = salaries * 1.10
print(hike)

#tought to solve but i did it

import numpy as np
import pandas as pd

# Random candidate data generate karo
np.random.seed(42)

names      = ["Devansh", "Rahul", "Priya",
              "John", "Sara", "Mike"]
scores     = np.random.randint(50, 100, 6)
salaries   = np.random.randint(40000, 120000, 6)
experience = np.random.randint(1, 8, 6)

df = pd.DataFrame({
    "Name"      : names,
    "Score"     : scores,
    "Salary"    : salaries,
    "Experience": experience
})

print("=== Candidate Data ===")
print(df)
print(f"\nAvg Score : {df['Score'].mean():.1f}")
print(f"Avg Salary: {df['Salary'].mean():.0f}")

# Filter karo
shortlisted = df[
    (df["Score"] >= 70) &
    (df["Experience"] >= 2)
]
print("\n=== Shortlisted ===")
print(shortlisted)

# Sort karo
top = df.sort_values("Score", ascending=False)
print("\n=== Top Candidates ===")
print(top.head(3))

