# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dw85E8DxK7Y2tegswBF4EGXs5qn7GQFT
"""

import pandas as pd
print("pandas ready!")

import pandas as pd

data = {
    "Name"      : ["Devansh", "Rahul", "Priya"],
    "Role"      : ["AI Engineer", "Python Dev", "Data Scientist"],
    "Salary"    : [120000, 80000, 110000],
    "Experience": [3, 2, 4]

}
df = pd.DataFrame(data)
print(df)

import pandas as pd

data = {
    "Name" : ["Sanju", "Ritik", "Shivangi", "Gopu", "Vaibhav"],
    "Skills" : ["Java", "dot net", "AWS", "Python", "Linux"],
    "Salary" : [40000, 60000, 55000, 42000, 80000],
    "City" : ["Agra", "Auraiya", "Bhind", "Kanpur", "Delhi"],
    "Experience" : [1, 3, 2, 5, 4]
}
df = pd.DataFrame(data)
print(df)
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.head(2))
print(df.tail(2))
print(df.describe())

import pandas as pd

data = {
    "Name"      : ["Devansh", "Rahul", "Priya", "John", "Sara"],
    "Role"      : ["AI Engineer", "Python Dev", "Data Scientist",
                   "ML Engineer", "Java Dev"],
    "Salary"    : [120000, 80000, 110000, 95000, 70000],
    "Experience": [3, 2, 4, 3, 1],
    "City"      : ["Delhi", "Mumbai", "Pune", "Delhi", "Bangalore"]
}
df = pd.DataFrame(data)
print(df["Name"])
print(df["Salary"])
print(df[["Name", "Salary"]])
print(df["Salary"].mean())
print(df["Salary"].max())
print(df["Salary"].sum())
print(df["Salary"].min())

import pandas as pd

data = {
    "Name"      : ["Sanju", "Ritik", "Shivangi",
                   "Gopu", "Vaibhav"],
    "Skills"    : ["Java", "Python", "AWS",
                   "Python", "Linux"],
    "Salary"    : [40000, 60000, 55000, 42000, 80000],
    "City"      : ["Agra", "Delhi", "Bhind",
                   "Kanpur", "Delhi"],
    "Experience": [1, 3, 2, 5, 4]
}
df = pd.DataFrame(data)
print (df[df["Salary"]>50000])

import pandas as pd

data = {
    "Name"      : ["Sanju", "Ritik", "Shivangi",
                   "Gopu", "Vaibhav"],
    "Skills"    : ["Java", "Python", "AWS",
                   "Python", "Linux"],
    "Salary"    : [40000, 60000, 55000, 42000, 80000],
    "City"      : ["Agra", "Delhi", "Bhind",
                   "Kanpur", "Delhi"],
    "Experience": [1, 3, 2, 5, 4]
}
df = pd.DataFrame(data)
print(df[df["City"]=="Delhi"])

import pandas as pd

data = {
    "Name"      : ["Sanju", "Ritik", "Shivangi",
                   "Gopu", "Vaibhav"],
    "Skills"    : ["Java", "Python", "AWS",
                   "Python", "Linux"],
    "Salary"    : [40000, 60000, 55000, 42000, 80000],
    "City"      : ["Agra", "Delhi", "Bhind",
                   "Kanpur", "Delhi"],
    "Experience": [1, 3, 2, 5, 4]
}
0df = pd.DataFrame(data)
print(df[df["Experience"]>=3])

import pandas as pd

data = {
    "Name"      : ["Sanju", "Ritik", "Shivangi",
                   "Gopu", "Vaibhav"],
    "Skills"    : ["Java", "Python", "AWS",
                   "Python", "Linux"],
    "Salary"    : [40000, 60000, 55000, 42000, 80000],
    "City"      : ["Agra", "Delhi", "Bhind",
                   "Kanpur", "Delhi"],
    "Experience": [1, 3, 2, 5, 4]
}
df = pd.DataFrame(data)
print(df[(df["Salary"]>50000) & (df["City"] == "Delhi")])

import pandas as pd

data = {
    "Name"      : ["Sanju", "Ritik", "Shivangi",
                   "Gopu", "Vaibhav"],
    "Skills"    : ["Java", "Python", "AWS",
                   "Python", "Linux"],
    "Salary"    : [40000, 60000, 55000, 42000, 80000],
    "City"      : ["Agra", "Delhi", "Bhind",
                   "Kanpur", "Delhi"],
    "Experience": [1, 3, 2, 5, 4]
}
df = pd.DataFrame(data)
print(df[(["City"]=="Delhi") | (df["City"]=="Kanpur")])

import pandas as pd

data = {
    "Name"      : ["Sanju", "Ritik", "Shivangi",
                   "Gopu", "Vaibhav"],
    "Skills"    : ["Java", "Python", "AWS",
                   "Python", "Linux"],
    "Salary"    : [40000, 60000, 55000, 42000, 80000],
    "City"      : ["Agra", "Delhi", "Bhind",
                   "Kanpur", "Delhi"],
    "Experience": [1, 3, 2, 5, 4]
}
df = pd.DataFrame(data)
df_sort = df.sort_values("Salary", ascending = False)
print(df_sort)

import pandas as pd
data = {
    "Name" : ["Sanju", "Shekhar", "Nisha", "Vishak", "Ritik"],
    "Age" : [24, 22, 25, 26, 19],
    "City" :  ["Pune", "Delhi", "Agra", "Churu", "Mahoba"],
    "Hobby" : ["Tennis", "Chess", "Racket", "Baseball", "Hockey"],
    "Phone_brand" : ["Nokia", "Moto", "Apple", "Pixle", "Redmi"]
}
df = pd.DataFrame(data)
print(df)
print(df.head(3))
print(df.tail(2))

import pandas as pd
data = {
    "Name" : ["Sanju", "Shekhar", "Nisha", "Vishak", "Ritik"],
    "Age" : [24, 22, 25, 26, 19],
    "City" :  ["Pune", "Delhi", "Agra", "Churu", "Mahoba"],
    "Hobby" : ["Tennis", "Chess", "Racket", "Baseball", "Hockey"],
    "Phone_brand" : ["Nokia", "Moto", "Apple", "Pixle", "Redmi"]
}
df = pd.DataFrame(data)
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.describe())

# Job data banao:
# Title, Company, Salary, City, Remote
# 5 jobs daalo
# 1. Sirf Title column print karo
# 2. Title aur Salary dono print karo
# 3. Salary ka mean nikalo
# 4. Salary ka max nikalo
# 5. Salary ka min nikalo
# 6. Salary ka sum nikalo

import pandas as pd
data = {
    "Title" : ["Python Dev", "Java Dev", "Node Engineer", "SDE", "AI Engineer"],
    "Company" : ["Nokia", "Apple", "Google", "Samsung", "Open AI"],
    "Salary" : [100000, 50000, 70000, 62000, 39000],
    "City" : ["Pune", "Delhi", "Agra", "Churu", "Mahoba"],
    "Remote" : ["Yes", "Yes", "No", "Yes", "No"]
}
df = pd.DataFrame(data)
print(df)
print(df.Title)
print(df [["Title", "Salary"]])
print("Mean Salary:", df["Salary"].mean())
print("Max Salary:", df["Salary"].max())
print("Minimum Salary:", df["Salary"].min())
print("Sum Of Salary:", df["Salary"].sum())

# Candidates data banao:
# Name, Experience, Score, City, Salary
# 6 candidates daalo
# Filter karo:
# 1. Score > 75 wale
# 2. City == "Delhi" wale
# 3. Experience >= 3 wale
# 4. Salary <= 60000 wale

import pandas as pd
candidate_data = {
    "Name" : ["Sanju", "Shekhar", "Nisha", "Vishal", "Ritik", "Vaibhav"],
    "Experience" : [6, 5, 7, 2, 3, 7],
    "Score" : [68, 79, 55, 83, 90, 75],
    "City" : ["Pune", "Delhi", "Agra", "Churu", "Delhi", "Auraiya"],
    "Salary" : [100000, 50000, 70000, 62000, 39000, 67000]
}
df = pd.DataFrame(candidate_data)
print(df[df["Score"]>75])
print(df[df["City"]=="Delhi"])
print(df[df["Experience"]>=3])
print(df[df["Salary"]<=60000])

# Same data use karo
# Filter karo:
# 1. Score > 75 AND Experience >= 3
# 2. City == "Delhi" AND Salary > 50000
# 3. City == "Delhi" OR City == "Mumbai"
# 4. Experience >= 2 AND Score > 70
#    AND Salary > 45000


import pandas as pd
candidate_data = {
    "Name" : ["Sanju", "Shekhar", "Nisha", "Vishal", "Ritik", "Vaibhav"],
    "Experience" : [6, 5, 7, 2, 3, 7],
    "Score" : [68, 79, 55, 83, 90, 75],
    "City" : ["Pune", "Delhi", "Agra", "Churu", "Delhi", "Mumbai"],
    "Salary" : [100000, 50000, 70000, 62000, 39000, 67000]
}
df = pd.DataFrame(candidate_data)
print(df[(df["Score"]>75) & (df["Experience"]>3)])
print(df[(df["City"]=="Delhi") & (df["Salary"]>50000)])
print(df[(df["City"]=="Delhi") | (df["City"]=="Mumbai")])
print(df[(df["Experience"]>=2) & (df["Score"]>70) & (df["Salary"]>45000)])

# Job postings data banao:
# Title, Salary, Experience, City
# 5 jobs
# 1. Salary ascending sort
# 2. Salary descending sort
# 3. Experience ascending sort
# 4. City alphabetical sort
# 5. Experience desc + Salary desc

import pandas as pd

job_data = {
    "Title": [
        "Python Developer",
        "AI Engineer",
        "Data Scientist",
        "ML Engineer",
        "Backend Developer",
        "DevOps Engineer"
    ],

    "Salary": [
        70000,
        120000,
        110000,
        95000,
        80000,
        90000
    ],

    "Experience": [
        1,
        3,
        2,
        4,
        2,
        3
    ],

    "City": [
        "Delhi",
        "Noida",
        "Bangalore",
        "Pune",
        "Gurgaon",
        "Mumbai"
    ]
}

df = pd.DataFrame(job_data)

print(df.sort_values(by="Salary", ascending = True))
print(df.sort_values(by="Salary", ascending=False))
print(df.sort_values(by = "Experience", ascending=True))
print(df.sort_values(by="City", ascending = True))
print(df.sort_values(by=["Experience", "Salary"], ascending =[False, False]))

import pandas as pd
data = {
    "Title" : ["Python Dev", "Java Dev", "Node Engineer", "SDE", "AI Engineer"],
    "Experience" : [3, 6, 7, 2, 1],
    "Salary" : [100000, 50000, 70000, 62000, 39000],
    "City" : ["Pune", "Delhi", "Agra", "Churu", "Mahoba"],
}
df = pd.DataFrame(data)

