# -*- coding: utf-8 -*-
"""practicalproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yn_b7i1MECQ8Lpv5Kv8JeQCotVjReOwD
"""

jobs = [
    {"title": "AI Engineer",     "skills": ["Python", "AI", "ML"],        "location": "Delhi",  "salary": 120000},
    {"title": "Python Dev",      "skills": ["Python", "Django"],           "location": "Mumbai", "salary": 80000},
    {"title": "ML Engineer",     "skills": ["ML", "Python"],               "location": "Delhi",  "salary": 95000},
    {"title": "Data Scientist",  "skills": ["ML", "Data Science"],         "location": "Pune",   "salary": 110000},
    {"title": "Java Dev",        "skills": ["Java", "Spring"],             "location": "Pune",   "salary": 75000},
    {"title": "Web Developer",   "skills": ["HTML", "CSS", "JavaScript"],  "location": "Mumbai", "salary": 70000},
    {"title": "DevOps Engineer", "skills": ["Docker", "Kubernetes", "CI"], "location": "Delhi",  "salary": 100000},
]

required_ai_skills = ["Python", "AI", "ML"]

print("✅ Database loaded!")
import datetime

def get_user_input():
    print("\n" + "=" * 45)
    print("   📋 ENTER YOUR DETAILS")
    print("=" * 45)

    name       = input("  Your Name        : ")
    location   = input("  Your Location    : ")
    experience = int(input("  Experience (yrs) : "))
    salary     = int(input("  Expected Salary  : "))

    print("\n  Enter skills (comma separated)")
    print("  Example: Python, AI, ML, Django")
    skills_input = input("  Your Skills      : ")
    skills = [s.strip() for s in skills_input.split(",")]

    candidate = {
        "name":            name,
        "location":        location,
        "experience":      experience,
        "expected_salary": salary,
        "skills":          skills
    }
    return candidate


import datetime

def get_user_input():
    print("\n" + "=" * 45)
    print("   📋 ENTER YOUR DETAILS")
    print("=" * 45)

    name       = input("  Your Name        : ")
    location   = input("  Your Location    : ")
    experience = int(input("  Experience (yrs) : "))
    salary     = int(input("  Expected Salary  : "))

    print("\n  Enter skills (comma separated)")
    print("  Example: Python, AI, ML, Django")
    skills_input = input("  Your Skills      : ")
    skills = [s.strip() for s in skills_input.split(",")]

    candidate = {
        "name":            name,
        "location":        location,
        "experience":      experience,
        "expected_salary": salary,
        "skills":          skills
    }
    return candidate



def parse_resume(candidate):
    print("\n" + "=" * 45)
    print("   📄 YOUR RESUME ANALYSIS")
    print("=" * 45)
    print(f"  Name        : {candidate['name']}")
    print(f"  Location    : {candidate['location']}")
    print(f"  Experience  : {candidate['experience']} years")
    print(f"  Skills      : {', '.join(candidate['skills'])}")
    print(f"  Exp. Salary : ₹{candidate['expected_salary']:,}")

    matched = 0
    for skill in required_ai_skills:
        if skill in candidate["skills"]:
            matched += 1

    match_percent = (matched / len(required_ai_skills)) * 100
    print(f"\n  AI Match    : {match_percent:.0f}%")

    if match_percent >= 80:
        print("  Profile     : 🔥 Strong AI Candidate!")
    elif match_percent >= 50:
        print("  Profile     : 👍 Good Candidate!")
    else:
        print("  Profile     : ⚠️  Build More AI Skills!")

    return match_percent



def match_jobs(candidate):
    print("\n" + "=" * 45)
    print("   🎯 BEST JOB MATCHES FOR YOU")
    print("=" * 45)

    results = []

    for job in jobs:
        job_skills = job["skills"]
        job_salary = job["salary"]

        matched = 0
        for skill in job_skills:
            if skill in candidate["skills"]:
                matched += 1

        score = (matched / len(job_skills)) * 100

        if job_salary >= candidate["expected_salary"]:
            salary_ok = "✅"
        else:
            salary_ok = "❌"

        results.append({
            "title":    job["title"],
            "score":    score,
            "salary":   job_salary,
            "salary_ok": salary_ok
        })


    results.sort(key=lambda x: x["score"], reverse=True)


    print(f"\n  {'Job Title':<20} {'Match':>6}  {'Salary':>10}  {'OK':>4}")
    print("  " + "-" * 46)
    for r in results[:3]:
        print(f"  {r['title']:<20} {r['score']:>5.0f}%  ₹{r['salary']:>9,}  {r['salary_ok']:>4}")

    best = results[0]
    print(f"\n  🏆 Best Match → {best['title']} ({best['score']:.0f}% match)")

    return results

def save_results(candidate, match_percent, results):
    time_now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")

    with open("results.txt", "a") as file:
        file.write("\n" + "=" * 45 + "\n")
        file.write(f"  Date     : {time_now}\n")
        file.write(f"  Name     : {candidate['name']}\n")
        file.write(f"  Skills   : {', '.join(candidate['skills'])}\n")
        file.write(f"  AI Match : {match_percent:.0f}%\n")
        file.write(f"\n  Top Matches:\n")
        for r in results[:3]:
            file.write(f"  → {r['title']:<20} {r['score']:.0f}% match\n")
        file.write("=" * 45 + "\n")

    print(f"\n  ✅ Results saved to results.txt!")

print("✅ All functions ready!")

def main():
    print("\n" + "=" * 45)
    print("   🤖 AI JOB MATCHER SYSTEM")
    print("   By Devansh | Delhi NCR AI Engineer")
    print("=" * 45)

    while True:
        print("\n  What do you want to do?")
        print("  1 → Find My Best Job Match")
        print("  2 → View Saved Results")
        print("  3 → Exit")

        choice = input("\n  Enter choice (1/2/3): ")

        if choice == "1":
            candidate = get_user_input()       # Step 1 — input lo
            match_pct = parse_resume(candidate) # Step 2 — resume analyze karo
            results   = match_jobs(candidate)   # Step 3 — jobs match karo
            save_results(candidate, match_pct, results) # Step 4 — save karo

        elif choice == "2":
            print("\n" + "=" * 45)
            print("   📁 SAVED RESULTS")
            print("=" * 45)
            try:
                with open("results.txt", "r") as file:
                    print(file.read())
            except:
                print("  No results saved yet!")

        elif choice == "3":
            print("\n  👋 All the best Devansh — AI Engineer bante raho!")
            print("=" * 45 + "\n")
            break

        else:
            print("  ❌ Invalid — 1, 2 ya 3 enter karo!")

main()

